[Settings]

# All netfliy options should be defined here. UI options should stay empty.

[build]
base = ""
publish = "website/public"

# Our Makefile build hugo, but it's faster if netlify grab the correct version on their own
# via simple curl.
environment = { HUGO_VERSION="0.55.3" }

# NOTE: Sleep at then is to make sure logs are not truncated on error.
command = "(env && make web HUGO=$(which hugo)) || (sleep 30; false)"

[context.deploy-preview]

# NOTE: Sleep at then is to make sure logs are not truncated on error.
command = "(env && make web HUGO=$(which hugo) WEBSITE_BASE_URL=${DEPLOY_PRIME_URL}) || (sleep 30; false)"

[[headers]]
  for = "/*"
  [headers.values]
    # We don't use iframes. Block them.
    X-Frame-Options = "DENY"
    # Don'a allow Mime-sniffing.
    X-Content-Type-Options = "nosniff"
    # Add reflective XSS protection.
    X-XSS-Protection = "1; mode=block"
    # Force HTTPS only.
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    # Load scripts only via https and from white listed domains.
    Content-Security-Policy = "default-src https:; script-src thanos.io"
    # Only send referred when HTTPS is used.
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Disable certain magic feature, lol.
    Feature-Policy = "vibrate none; usermedia *; sync-xhr self"