apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-gcs
  labels:
    app: prometheus-gcs
    thanos-peer: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-gcs
        thanos-peer: "true"
    spec:
      containers:
      - image: prom/prometheus:v2.0.0
        args: [
          "--config.file=/etc/prometheus/config/prometheus.yaml",
          "--storage.tsdb.path=/data",
          "--storage.tsdb.min-block-duration=2h",
          "--storage.tsdb.max-block-duration=2h",
          "--storage.tsdb.retention=12h"
        ]
        name: prometheus
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/config
        - name: tsdb-data
          mountPath: /data
        # To use your own thanos image you need to do `eval $(minikube docker-env) && make docker` and place thanos/thanos:latest here.
        # TODO(bplotka): With vm-driver=none, even that is uses same docker, images are not recognized. Investigate.
      - image: bplotka/thanos:latest
        imagePullPolicy: Always
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /creds/gcs-credentials.json
        args: [
          "sidecar",
          "--log.level=debug",
          "--debug.name=sidecar",
          "--api-address=0.0.0.0:19090", # This address will be properly deduced and propagated via cluster.PeerState.
          "--metrics-address=0.0.0.0:19190",
          "--prometheus.url=http://localhost:9090",
          "--tsdb.path=/data",
          "--cluster.address=0.0.0.0:19390",
          "--cluster.peers=thanos.default.svc.cluster.local:19390",
          # This is required to be added in GCS prior startup of this.
          "--gcs.bucket=thanos-test"
        ]
        name: thanos
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - name: tsdb-data
          mountPath: /data
        - name: gcs-credentials
          mountPath: /creds/
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-gcs
      - name: tsdb-data
        emptyDir: {}
      - name: gcs-credentials
        secret:
          defaultMode: 420
          # gcs-credentials secret with single file gcs-credentials.json is required.
          secretName: gcs-credentials
      terminationGracePeriodSeconds: 300