apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-store
  name: thanos-store
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 19190
    protocol: TCP
    targetPort: 19190
    name: http-store-metrics
  selector:
    app: thanos-query
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
