apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: thanos-query
  labels:
    app: thanos-query
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
        # To use your own thanos image you need to do `eval $(minikube docker-env) && make docker` and place thanos/thanos:latest here.
        # TODO(bplotka): With vm-driver=none, even that is uses same docker, images are not recognized. Investigate.
      - image: bplotka/thanos:latest
        imagePullPolicy: Always
        args: [
          "query",
          "--debug.name=query",
          "--api-address=0.0.0.0:19099",
          "--cluster.address=0.0.0.0:19399",
          "--cluster.advertise-address=10.0.0.89:19399",
          "--cluster.peers", "10.0.0.88:19391" # Sidecar from manifest/prometheus
        ]
        name: thanos
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
      terminationGracePeriodSeconds: 300