apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-query
  name: thanos-query
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 19099
    protocol: TCP
    targetPort: 19099
    name: http-query
  selector:
    app: thanos-query
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
