name: CI
on: [pull_request]

jobs:
  cross-build-check:
    name: Cross build check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        run: make deps

      - name: Cross build check
        run: make crossbuild
