name: CI
on: [pull_request]

jobs:
  cross-build-check:
    name: Cross build check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        run: make deps

      - name: Cross build check
        run: make crossbuild
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    # Build by Thanos make docker-ci
    container: quay.io/thanos/thanos-ci:v0.2.0
    env:
      GOBIN: "/go/bin"
    steps:
      - name: Init
        run: |
          sh -c "sudo chown -R circleci /github"
          sh -c "sudo chmod -R 777 /github"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        run: make deps

      ## Standard setup above.

      - name: Linting
        run: make lint
  check-docs:
    name: Docs check
    runs-on: ubuntu-latest
    # Build by Thanos make docker-ci
    container: quay.io/thanos/thanos-ci:v0.2.0
    env:
      GOBIN: "/go/bin"
    steps:
      - name: Init
        run: |
          sh -c "sudo chown -R circleci /github"
          sh -c "sudo chmod -R 777 /github"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        run: make deps

      ## Standard setup above.

      - name: Docs checking
        run: make docs
