name: CI
on: [pull_request]
jobs:
  cross-build-check:
    name: Cross build check
    runs-on: ubuntu-latest
    # Build by Thanos make docker-ci
    container: quay.io/thanos/thanos-ci:v0.2.0
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: make deps

    - name: Cross build check
      run: make crossbuild
  lint:
    name: Build2
    runs-on: ubuntu-latest
    # Build by Thanos make docker-ci
    container: quay.io/thanos/thanos-ci:v0.2.0
    steps:
    - name: Linting
      run: make lint
